# yaml-language-server: $schema=./suite.schema.json

jobs:
  - id: overnight-multi
    label: Overnight Multi
    parameters:
      - parameters/linear.yaml
      - parameters/experiments/leios-fixed-price-eb-on.yaml
    compare-parameters:
      - parameters/experiments/leios-tiered-continuous-rbeb-reject-inline.yaml
      - parameters/experiments/leios-tiered-continuous-rbeb-reject-either-or.yaml
      - parameters/experiments/leios-tiered-continuous-rbeb-reject-inline-overflow-aggregate.yaml
      - parameters/experiments/leios-tiered-continuous-rbeb-reject-inline-overflow-tier-pressure.yaml
      - parameters/experiments/leios-tiered-naive-rb-eb.yaml
      - parameters/experiments/leios-tiered-naive-rb-eb-inclusive.yaml
    slots: 2000
    trace: false
